[book]
authors = ["Tang Ziya"]
language = "en"
multilingual = true
src = "src"
title = "Tang's blog"

[build]
extra-watch-dirs = ["po"]

[preprocessor.bib]
bibliography = "literature.bib"

[preprocessor.gettext]
after = ["links"]
